# Generated by Django 5.0.14 on 2025-06-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0002_alter_winepost_author_remove_winepost_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
