# Generated by Django 5.0.14 on 2025-06-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0004_comment_delete_user_winepost_updated_on_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winepost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
